# Modification pour forcer rechargement des variables
name: Scrape LeBonCoin

on:
  schedule:
    - cron: '0 * * * *'  # toutes les heures
  workflow_dispatch:      # exécution manuelle

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: DEBUG ENV
        run: |
          echo "📦 LBC_URL = $LBC_URL"
        env:
          LBC_URL: ${{ vars.LBC_URL }}
      - name: Run scraper
        run: echo "🔎 LBC_URL transmis à l’environnement : $LBC_URL"
        env:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          LBC_URL: ${{ vars.LBC_URL }}
        run: python scraper.py
