name: Test Env

on: [workflow_dispatch]

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
      - name: Print env vars
        env:
          LBC_URL: ${{ secrets.LBC_URL }}
        run: |
          echo "LBC_URL is $LBC_URL"
          env
