name: Scrape LeBonCoin with Selenium

on:
  schedule:
    - cron: '0 7,12,17 * * *'  # toute les 5 heures à partir de 7h00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux-signing-keyring.gpg
          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version
  
      - name: Install ChromeDriver manually (compatible with Chrome 138)
        run: |
          DRIVER_VERSION=138.0.0.0
          echo "Using ChromeDriver version: $DRIVER_VERSION"
          wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
          chromedriver --version
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        env:
          LBC_URL: ${{ vars.LBC_URL }}
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python scraper_selenium.py
