name: Scrape LeBonCoin with Selenium

on:
  schedule:
    - cron: '0 * * * *'  # chaque heure
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 requests

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1)
          wget https://chromedriver.storage.googleapis.com/${CHROME_VERSION}.0.0/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip

      - name: Run scraper
        env:
          LBC_URL: ${{ vars.LBC_URL }}
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python scraper_selenium.py
